REVOKE ALL ON FUNCTION public.admin_close_support_view(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_open_support_view(uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_review_recharge(uuid, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_review_withdrawal(uuid, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.consume_welcome_bonus_popup() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_admin_dashboard() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_my_daily_wheel_state() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_my_invite_task_state() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_my_referral_dashboard() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_my_reward_summary() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_my_withdrawal_eligibility() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.process_my_vehicle_rewards() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.purchase_vehicle(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.redeem_credit_code(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.renew_vehicle(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.request_demo_recharge(numeric) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.request_withdrawal(numeric, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.request_withdrawal(numeric, text, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.spin_daily_wheel() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.transfer_my_vehicle_rewards() FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.admin_close_support_view(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_open_support_view(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_review_recharge(uuid, boolean) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_review_withdrawal(uuid, boolean) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.consume_welcome_bonus_popup() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_admin_dashboard() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_my_daily_wheel_state() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_my_invite_task_state() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_my_referral_dashboard() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_my_reward_summary() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_my_withdrawal_eligibility() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.process_my_vehicle_rewards() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.purchase_vehicle(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.redeem_credit_code(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.renew_vehicle(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.request_demo_recharge(numeric) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.spin_daily_wheel() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.transfer_my_vehicle_rewards() TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.validate_invite_code(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.validate_invite_code(text) TO anon, authenticated, service_role;